Add -m option for an alternative mount path
Also improve the -c option's clean out logic and more
sanity checks for existing mounts and previous mounts via
fstab entries.  Added a comment block to document the limitations
of the script.

Change-Id: I392c36ef9649e1dc7964809c6f5fde6835d91c17

diff --git a/ansible/roles/cloudstor/files/cloudstor-setup b/ansible/roles/cloudstor/files/cloudstor-setup
--- a/ansible/roles/cloudstor/files/cloudstor-setup
+++ b/ansible/roles/cloudstor/files/cloudstor-setup
@@ -12,6 +12,20 @@
 #  License for the specific language governing permissions and limitations
 #  under the License.
 
+set -x
+
+# Limitations
+# 1. Cleanup (-c) is not selective.  It gets rid of all previous
+#    CloudStore mounts and configs that it can find, for all users
+#    with little feedback 
+# 2. We don't deal with the case where the someone has set up a
+#    CloudStor mount by hand in an unexpected location.
+# 3. The mounted share is owned by the current user with access to
+#    others restricted by the user's netmask.
+# 4. Mount options are hard-wired
+# 5. We don't deal with mounting more than one CloudStor share at
+#    a time (for the entire instance.)
+
 # CloudStor details
 WEBDAV_URL=https://cloudstor.aarnet.edu.au/plus/remote.php/webdav/
 MOUNT_PATH=/cloudstor
@@ -19,6 +33,7 @@ MOUNT_PATH=/cloudstor
 cleanup=false
 username=
 password=
+mount_path=${MOUNT_PATH}
 
 usage() {
   cat >&2 << EOF
@@ -28,11 +43,30 @@ Options:
   -c     unmount and clean up any CloudStor config
   -u     username. if not given, you will be prompted
   -p     password. if not given, you will be prompted
+  -m     mount-directory. defaults to $MOUNT_PATH
   -h     this help message
 EOF
   exit 1
 }
 
+check_for_mount() {
+  if mountpoint -q "$1"; then
+    echo "A CloudStor share is already mounted at $1"
+    echo "To unmount all shares and clean up all previous CloudStore configs"
+    echo "and mount points, you can run '$0 -c'"  
+    exit 2
+  fi
+}
+
+delete_mount_point() {
+  if [ $# -gt 0 ]; then
+    if [ -d "$1" ]; then
+      echo "Removing old mountpoint $1"      
+      sudo rmdir "$1"
+    fi
+  fi
+}
+      
 # Should run as unpriv user, so we can use that user in fstab
 if [[ $UID == 0 ]]; then
   echo "This command should NOT be run as root"
@@ -40,7 +74,7 @@ if [[ $UID == 0 ]]; then
 fi
 
 
-while getopts "hcu:p:" opt; do
+while getopts "hcu:p:m:" opt; do
   case ${opt} in
     h)
       usage
@@ -54,6 +88,15 @@ while getopts "hcu:p:" opt; do
     p)
       password=${OPTARG}
       ;;
+    m)
+      mount_path=${OPTARG}
+      if [ "${mount_path#/}" = "${mount_path}" ]; then
+          echo "-m should give an absolute directory path"
+          usage
+      fi
+      # Should also check for white-space in the path because
+      # that is likely to mess up the fstab
+      ;;
     *)
       usage
       ;;
@@ -61,19 +104,50 @@ while getopts "hcu:p:" opt; do
 done
 shift $((OPTIND-1))
 
-# Clean up all traces of cloudstor mount setup
+# Clean up all traces of all previous cloudstor mounts.  We cannot
+# be selective because the secrets is common to all mounts.
 if [ "$cleanup" = true ]; then
   echo "Cleaning up CloudStor setup..."
-  if mountpoint -q $MOUNT_PATH; then
-    sudo umount $MOUNT_PATH
+  if mountpoint -q "$mount_path"; then
+    sudo umount "$mount_path"
   fi
-  sudo sed -i '\,^'"$WEBDAV_URL"',d' /etc/davfs2/secrets /etc/fstab
-  [ -d $MOUNT_PATH ] && sudo rmdir $MOUNT_PATH
+  if mountpoint -q "$MOUNT_PATH"; then
+    sudo umount "$MOUNT_PATH"
+  fi
+  grep -h "$WEBDAV_URL" /etc/fstab | {
+    read URL MP REST
+    if mountpoint -q "$MP"; then
+      sudo umount "$MP"
+    fi
+    delete_mount_point "$MP"
+  }
+  sudo sed -i '\,^'"$WEBDAV_URL"',d' /etc/fstab
+  [ -f /etc/davfs2/secrets ] && sudo sed -i '\,^'"$WEBDAV_URL"',d' /etc/davfs2/secrets
+  delete_mount_point "$mount_path"
+  delete_mount_point "$MOUNT_PATH"
   exit 0
 fi
 
-if mountpoint -q $MOUNT_PATH; then
-  echo "CloudStor already mounted at $MOUNT_PATH"
+# Check for active cloudstor mounts
+check_for_mount "$mount_path"
+check_for_mount "$MOUNT_PATH"
+
+# Deal with cases where cloudstor is or was mounted on some
+# other mount point (as recorded in the fstab).
+grep -h "$WEBDAV_URL" /etc/fstab | {
+  read URL MP REST
+  if [ $# -gt 0 ]; then
+    if [ "X$mount_path" != "X$MP" ] ; then
+      check_for_mount "$MP" || {
+        echo "CloudStor was previously mounted at $MP"
+        echo "To clean up all previous CloudStore mount configs"
+        echo "and mount points, you need to run '$0 -c'"
+      }
+      exit 2
+    fi
+  fi
+}
+if [ $? -eq 2 ] ; then
   exit 2
 fi
 
@@ -175,9 +249,9 @@ sudo sed -i '\,^'"$WEBDAV_URL"',d' /etc/davfs2/secrets
 escapedpassword=$(echo "$password" | sed 's/"/\\"/g')  # noqa
 echo "$WEBDAV_URL $username \"$escapedpassword\"" | sudo tee -a /etc/davfs2/secrets > /dev/null
 
-[ -d $MOUNT_PATH ] || sudo mkdir $MOUNT_PATH
+[ -d "$mount_path" ] || sudo mkdir "$mount_path"
 if ! grep -q "$WEBDAV_URL" /etc/fstab; then
-  echo "$WEBDAV_URL $MOUNT_PATH davfs uid=$USER,_netdev 0 0" | sudo tee -a /etc/fstab > /dev/null
+  echo "$WEBDAV_URL $mount_path davfs uid=$USER,_netdev 0 0" | sudo tee -a /etc/fstab > /dev/null
 fi
 
 # Explicitly disable locks - not supported by OwnCloud
@@ -185,9 +259,9 @@ sudo sed -i 's/.*use_locks.*/use_locks 0/g' /etc/davfs2/davfs2.conf
 
 # Perform mount
 echo -n "Mounting CloudStor storage... "
-if sudo mount $MOUNT_PATH; then
+if sudo mount "$mount_path"; then
   echo "done"
-  echo "Your CloudStor account has been mounted to $MOUNT_PATH"
+  echo "Your CloudStor account has been mounted to $mount_path"
   exit 0
 fi
 
